// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dervaze.proto

package dervaze

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SearchType int32

const (
	SearchType_PREFIX SearchType = 0
	SearchType_FUZZY  SearchType = 1
	SearchType_REGEX  SearchType = 2
)

var SearchType_name = map[int32]string{
	0: "PREFIX",
	1: "FUZZY",
	2: "REGEX",
}

var SearchType_value = map[string]int32{
	"PREFIX": 0,
	"FUZZY":  1,
	"REGEX":  2,
}

func (x SearchType) String() string {
	return proto.EnumName(SearchType_name, int32(x))
}

func (SearchType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f7e184749fd60cbd, []int{0}
}

type Req int32

const (
	Req_NEVER  Req = 0
	Req_MAYBE  Req = 1
	Req_ALWAYS Req = 2
)

var Req_name = map[int32]string{
	0: "NEVER",
	1: "MAYBE",
	2: "ALWAYS",
}

var Req_value = map[string]int32{
	"NEVER":  0,
	"MAYBE":  1,
	"ALWAYS": 2,
}

func (x Req) String() string {
	return proto.EnumName(Req_name, int32(x))
}

func (Req) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f7e184749fd60cbd, []int{1}
}

type PartOfSpeech int32

const (
	PartOfSpeech_NOUN        PartOfSpeech = 0
	PartOfSpeech_VERB        PartOfSpeech = 1
	PartOfSpeech_PROPER_NOUN PartOfSpeech = 2
)

var PartOfSpeech_name = map[int32]string{
	0: "NOUN",
	1: "VERB",
	2: "PROPER_NOUN",
}

var PartOfSpeech_value = map[string]int32{
	"NOUN":        0,
	"VERB":        1,
	"PROPER_NOUN": 2,
}

func (x PartOfSpeech) String() string {
	return proto.EnumName(PartOfSpeech_name, int32(x))
}

func (PartOfSpeech) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f7e184749fd60cbd, []int{2}
}

type TranslationDirection int32

const (
	TranslationDirection_tr2otm TranslationDirection = 0
	TranslationDirection_otm2tr TranslationDirection = 1
)

var TranslationDirection_name = map[int32]string{
	0: "tr2otm",
	1: "otm2tr",
}

var TranslationDirection_value = map[string]int32{
	"tr2otm": 0,
	"otm2tr": 1,
}

func (x TranslationDirection) String() string {
	return proto.EnumName(TranslationDirection_name, int32(x))
}

func (TranslationDirection) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f7e184749fd60cbd, []int{3}
}

type SearchRequest struct {
	// Types that are valid to be assigned to Field:
	//	*SearchRequest_Auto
	//	*SearchRequest_TurkishLatin
	//	*SearchRequest_Visenc
	//	*SearchRequest_Ottoman
	//	*SearchRequest_Abjad
	Field                isSearchRequest_Field `protobuf_oneof:"field"`
	SearchType           SearchType            `protobuf:"varint,14,opt,name=searchType,proto3,enum=dervaze.SearchType" json:"searchType,omitempty"`
	ResultLimit          int32                 `protobuf:"varint,15,opt,name=resultLimit,proto3" json:"resultLimit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e184749fd60cbd, []int{0}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

type isSearchRequest_Field interface {
	isSearchRequest_Field()
}

type SearchRequest_Auto struct {
	Auto string `protobuf:"bytes,1,opt,name=auto,proto3,oneof"`
}

type SearchRequest_TurkishLatin struct {
	TurkishLatin string `protobuf:"bytes,2,opt,name=turkishLatin,proto3,oneof"`
}

type SearchRequest_Visenc struct {
	Visenc string `protobuf:"bytes,3,opt,name=visenc,proto3,oneof"`
}

type SearchRequest_Ottoman struct {
	Ottoman string `protobuf:"bytes,4,opt,name=ottoman,proto3,oneof"`
}

type SearchRequest_Abjad struct {
	Abjad int32 `protobuf:"varint,7,opt,name=abjad,proto3,oneof"`
}

func (*SearchRequest_Auto) isSearchRequest_Field() {}

func (*SearchRequest_TurkishLatin) isSearchRequest_Field() {}

func (*SearchRequest_Visenc) isSearchRequest_Field() {}

func (*SearchRequest_Ottoman) isSearchRequest_Field() {}

func (*SearchRequest_Abjad) isSearchRequest_Field() {}

func (m *SearchRequest) GetField() isSearchRequest_Field {
	if m != nil {
		return m.Field
	}
	return nil
}

func (m *SearchRequest) GetAuto() string {
	if x, ok := m.GetField().(*SearchRequest_Auto); ok {
		return x.Auto
	}
	return ""
}

func (m *SearchRequest) GetTurkishLatin() string {
	if x, ok := m.GetField().(*SearchRequest_TurkishLatin); ok {
		return x.TurkishLatin
	}
	return ""
}

func (m *SearchRequest) GetVisenc() string {
	if x, ok := m.GetField().(*SearchRequest_Visenc); ok {
		return x.Visenc
	}
	return ""
}

func (m *SearchRequest) GetOttoman() string {
	if x, ok := m.GetField().(*SearchRequest_Ottoman); ok {
		return x.Ottoman
	}
	return ""
}

func (m *SearchRequest) GetAbjad() int32 {
	if x, ok := m.GetField().(*SearchRequest_Abjad); ok {
		return x.Abjad
	}
	return 0
}

func (m *SearchRequest) GetSearchType() SearchType {
	if m != nil {
		return m.SearchType
	}
	return SearchType_PREFIX
}

func (m *SearchRequest) GetResultLimit() int32 {
	if m != nil {
		return m.ResultLimit
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SearchRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SearchRequest_Auto)(nil),
		(*SearchRequest_TurkishLatin)(nil),
		(*SearchRequest_Visenc)(nil),
		(*SearchRequest_Ottoman)(nil),
		(*SearchRequest_Abjad)(nil),
	}
}

type OttomanWord struct {
	Visenc               string   `protobuf:"bytes,1,opt,name=visenc,proto3" json:"visenc,omitempty"`
	Unicode              string   `protobuf:"bytes,2,opt,name=unicode,proto3" json:"unicode,omitempty"`
	Abjad                int32    `protobuf:"varint,3,opt,name=abjad,proto3" json:"abjad,omitempty"`
	VisencLetters        []string `protobuf:"bytes,4,rep,name=visencLetters,proto3" json:"visencLetters,omitempty"`
	SearchKey            string   `protobuf:"bytes,5,opt,name=searchKey,proto3" json:"searchKey,omitempty"`
	DotlessSearchKey     string   `protobuf:"bytes,6,opt,name=dotlessSearchKey,proto3" json:"dotlessSearchKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OttomanWord) Reset()         { *m = OttomanWord{} }
func (m *OttomanWord) String() string { return proto.CompactTextString(m) }
func (*OttomanWord) ProtoMessage()    {}
func (*OttomanWord) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e184749fd60cbd, []int{1}
}

func (m *OttomanWord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OttomanWord.Unmarshal(m, b)
}
func (m *OttomanWord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OttomanWord.Marshal(b, m, deterministic)
}
func (m *OttomanWord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OttomanWord.Merge(m, src)
}
func (m *OttomanWord) XXX_Size() int {
	return xxx_messageInfo_OttomanWord.Size(m)
}
func (m *OttomanWord) XXX_DiscardUnknown() {
	xxx_messageInfo_OttomanWord.DiscardUnknown(m)
}

var xxx_messageInfo_OttomanWord proto.InternalMessageInfo

func (m *OttomanWord) GetVisenc() string {
	if m != nil {
		return m.Visenc
	}
	return ""
}

func (m *OttomanWord) GetUnicode() string {
	if m != nil {
		return m.Unicode
	}
	return ""
}

func (m *OttomanWord) GetAbjad() int32 {
	if m != nil {
		return m.Abjad
	}
	return 0
}

func (m *OttomanWord) GetVisencLetters() []string {
	if m != nil {
		return m.VisencLetters
	}
	return nil
}

func (m *OttomanWord) GetSearchKey() string {
	if m != nil {
		return m.SearchKey
	}
	return ""
}

func (m *OttomanWord) GetDotlessSearchKey() string {
	if m != nil {
		return m.DotlessSearchKey
	}
	return ""
}

type Root struct {
	TurkishLatin          string       `protobuf:"bytes,1,opt,name=turkishLatin,proto3" json:"turkishLatin,omitempty"`
	Ottoman               *OttomanWord `protobuf:"bytes,2,opt,name=ottoman,proto3" json:"ottoman,omitempty"`
	LastVowel             string       `protobuf:"bytes,3,opt,name=lastVowel,proto3" json:"lastVowel,omitempty"`
	LastConsonant         string       `protobuf:"bytes,4,opt,name=lastConsonant,proto3" json:"lastConsonant,omitempty"`
	EffectiveLastVowel    string       `protobuf:"bytes,5,opt,name=effectiveLastVowel,proto3" json:"effectiveLastVowel,omitempty"`
	EffectiveTurkishLatin string       `protobuf:"bytes,6,opt,name=effectiveTurkishLatin,proto3" json:"effectiveTurkishLatin,omitempty"`
	EffectiveVisenc       string       `protobuf:"bytes,7,opt,name=effectiveVisenc,proto3" json:"effectiveVisenc,omitempty"`
	Abjad                 int32        `protobuf:"varint,8,opt,name=abjad,proto3" json:"abjad,omitempty"`
	PartOfSpeech          PartOfSpeech `protobuf:"varint,9,opt,name=partOfSpeech,proto3,enum=dervaze.PartOfSpeech" json:"partOfSpeech,omitempty"`
	EndsWithVowel         bool         `protobuf:"varint,16,opt,name=endsWithVowel,proto3" json:"endsWithVowel,omitempty"`
	HasSingleVowel        bool         `protobuf:"varint,17,opt,name=hasSingleVowel,proto3" json:"hasSingleVowel,omitempty"`
	LastVowelHard         bool         `protobuf:"varint,18,opt,name=lastVowelHard,proto3" json:"lastVowelHard,omitempty"`
	LastConsonantHard     bool         `protobuf:"varint,19,opt,name=lastConsonantHard,proto3" json:"lastConsonantHard,omitempty"`
	HasConsonantSoftening bool         `protobuf:"varint,20,opt,name=hasConsonantSoftening,proto3" json:"hasConsonantSoftening,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}     `json:"-"`
	XXX_unrecognized      []byte       `json:"-"`
	XXX_sizecache         int32        `json:"-"`
}

func (m *Root) Reset()         { *m = Root{} }
func (m *Root) String() string { return proto.CompactTextString(m) }
func (*Root) ProtoMessage()    {}
func (*Root) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e184749fd60cbd, []int{2}
}

func (m *Root) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Root.Unmarshal(m, b)
}
func (m *Root) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Root.Marshal(b, m, deterministic)
}
func (m *Root) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Root.Merge(m, src)
}
func (m *Root) XXX_Size() int {
	return xxx_messageInfo_Root.Size(m)
}
func (m *Root) XXX_DiscardUnknown() {
	xxx_messageInfo_Root.DiscardUnknown(m)
}

var xxx_messageInfo_Root proto.InternalMessageInfo

func (m *Root) GetTurkishLatin() string {
	if m != nil {
		return m.TurkishLatin
	}
	return ""
}

func (m *Root) GetOttoman() *OttomanWord {
	if m != nil {
		return m.Ottoman
	}
	return nil
}

func (m *Root) GetLastVowel() string {
	if m != nil {
		return m.LastVowel
	}
	return ""
}

func (m *Root) GetLastConsonant() string {
	if m != nil {
		return m.LastConsonant
	}
	return ""
}

func (m *Root) GetEffectiveLastVowel() string {
	if m != nil {
		return m.EffectiveLastVowel
	}
	return ""
}

func (m *Root) GetEffectiveTurkishLatin() string {
	if m != nil {
		return m.EffectiveTurkishLatin
	}
	return ""
}

func (m *Root) GetEffectiveVisenc() string {
	if m != nil {
		return m.EffectiveVisenc
	}
	return ""
}

func (m *Root) GetAbjad() int32 {
	if m != nil {
		return m.Abjad
	}
	return 0
}

func (m *Root) GetPartOfSpeech() PartOfSpeech {
	if m != nil {
		return m.PartOfSpeech
	}
	return PartOfSpeech_NOUN
}

func (m *Root) GetEndsWithVowel() bool {
	if m != nil {
		return m.EndsWithVowel
	}
	return false
}

func (m *Root) GetHasSingleVowel() bool {
	if m != nil {
		return m.HasSingleVowel
	}
	return false
}

func (m *Root) GetLastVowelHard() bool {
	if m != nil {
		return m.LastVowelHard
	}
	return false
}

func (m *Root) GetLastConsonantHard() bool {
	if m != nil {
		return m.LastConsonantHard
	}
	return false
}

func (m *Root) GetHasConsonantSoftening() bool {
	if m != nil {
		return m.HasConsonantSoftening
	}
	return false
}

type RootSet struct {
	Roots                []*Root  `protobuf:"bytes,1,rep,name=roots,proto3" json:"roots,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RootSet) Reset()         { *m = RootSet{} }
func (m *RootSet) String() string { return proto.CompactTextString(m) }
func (*RootSet) ProtoMessage()    {}
func (*RootSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e184749fd60cbd, []int{3}
}

func (m *RootSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RootSet.Unmarshal(m, b)
}
func (m *RootSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RootSet.Marshal(b, m, deterministic)
}
func (m *RootSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RootSet.Merge(m, src)
}
func (m *RootSet) XXX_Size() int {
	return xxx_messageInfo_RootSet.Size(m)
}
func (m *RootSet) XXX_DiscardUnknown() {
	xxx_messageInfo_RootSet.DiscardUnknown(m)
}

var xxx_messageInfo_RootSet proto.InternalMessageInfo

func (m *RootSet) GetRoots() []*Root {
	if m != nil {
		return m.Roots
	}
	return nil
}

type Suffix struct {
	TurkishLatin               string       `protobuf:"bytes,1,opt,name=turkishLatin,proto3" json:"turkishLatin,omitempty"`
	Ottoman                    *OttomanWord `protobuf:"bytes,2,opt,name=ottoman,proto3" json:"ottoman,omitempty"`
	MorphologicalClass         string       `protobuf:"bytes,3,opt,name=morphologicalClass,proto3" json:"morphologicalClass,omitempty"`
	RequiredLastVowel          string       `protobuf:"bytes,4,opt,name=requiredLastVowel,proto3" json:"requiredLastVowel,omitempty"`
	RequiresPOS                PartOfSpeech `protobuf:"varint,5,opt,name=requiresPOS,proto3,enum=dervaze.PartOfSpeech" json:"requiresPOS,omitempty"`
	RequiresEndsWithVowel      Req          `protobuf:"varint,6,opt,name=requiresEndsWithVowel,proto3,enum=dervaze.Req" json:"requiresEndsWithVowel,omitempty"`
	RequiresHasSingleVowel     Req          `protobuf:"varint,7,opt,name=requiresHasSingleVowel,proto3,enum=dervaze.Req" json:"requiresHasSingleVowel,omitempty"`
	RequiresLastConsonantHard  Req          `protobuf:"varint,8,opt,name=requiresLastConsonantHard,proto3,enum=dervaze.Req" json:"requiresLastConsonantHard,omitempty"`
	SetsLastVowelTo            string       `protobuf:"bytes,9,opt,name=setsLastVowelTo,proto3" json:"setsLastVowelTo,omitempty"`
	RequiresContinuationSuffix Req          `protobuf:"varint,10,opt,name=requiresContinuationSuffix,proto3,enum=dervaze.Req" json:"requiresContinuationSuffix,omitempty"`
	InvalidateSuffixClasses    []string     `protobuf:"bytes,11,rep,name=invalidateSuffixClasses,proto3" json:"invalidateSuffixClasses,omitempty"`
	ConvertsPOSto              PartOfSpeech `protobuf:"varint,12,opt,name=convertsPOSto,proto3,enum=dervaze.PartOfSpeech" json:"convertsPOSto,omitempty"`
	EndsWithVowel              bool         `protobuf:"varint,13,opt,name=endsWithVowel,proto3" json:"endsWithVowel,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}     `json:"-"`
	XXX_unrecognized           []byte       `json:"-"`
	XXX_sizecache              int32        `json:"-"`
}

func (m *Suffix) Reset()         { *m = Suffix{} }
func (m *Suffix) String() string { return proto.CompactTextString(m) }
func (*Suffix) ProtoMessage()    {}
func (*Suffix) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e184749fd60cbd, []int{4}
}

func (m *Suffix) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Suffix.Unmarshal(m, b)
}
func (m *Suffix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Suffix.Marshal(b, m, deterministic)
}
func (m *Suffix) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Suffix.Merge(m, src)
}
func (m *Suffix) XXX_Size() int {
	return xxx_messageInfo_Suffix.Size(m)
}
func (m *Suffix) XXX_DiscardUnknown() {
	xxx_messageInfo_Suffix.DiscardUnknown(m)
}

var xxx_messageInfo_Suffix proto.InternalMessageInfo

func (m *Suffix) GetTurkishLatin() string {
	if m != nil {
		return m.TurkishLatin
	}
	return ""
}

func (m *Suffix) GetOttoman() *OttomanWord {
	if m != nil {
		return m.Ottoman
	}
	return nil
}

func (m *Suffix) GetMorphologicalClass() string {
	if m != nil {
		return m.MorphologicalClass
	}
	return ""
}

func (m *Suffix) GetRequiredLastVowel() string {
	if m != nil {
		return m.RequiredLastVowel
	}
	return ""
}

func (m *Suffix) GetRequiresPOS() PartOfSpeech {
	if m != nil {
		return m.RequiresPOS
	}
	return PartOfSpeech_NOUN
}

func (m *Suffix) GetRequiresEndsWithVowel() Req {
	if m != nil {
		return m.RequiresEndsWithVowel
	}
	return Req_NEVER
}

func (m *Suffix) GetRequiresHasSingleVowel() Req {
	if m != nil {
		return m.RequiresHasSingleVowel
	}
	return Req_NEVER
}

func (m *Suffix) GetRequiresLastConsonantHard() Req {
	if m != nil {
		return m.RequiresLastConsonantHard
	}
	return Req_NEVER
}

func (m *Suffix) GetSetsLastVowelTo() string {
	if m != nil {
		return m.SetsLastVowelTo
	}
	return ""
}

func (m *Suffix) GetRequiresContinuationSuffix() Req {
	if m != nil {
		return m.RequiresContinuationSuffix
	}
	return Req_NEVER
}

func (m *Suffix) GetInvalidateSuffixClasses() []string {
	if m != nil {
		return m.InvalidateSuffixClasses
	}
	return nil
}

func (m *Suffix) GetConvertsPOSto() PartOfSpeech {
	if m != nil {
		return m.ConvertsPOSto
	}
	return PartOfSpeech_NOUN
}

func (m *Suffix) GetEndsWithVowel() bool {
	if m != nil {
		return m.EndsWithVowel
	}
	return false
}

type SuffixSet struct {
	Suffixes             []*Suffix `protobuf:"bytes,1,rep,name=suffixes,proto3" json:"suffixes,omitempty"`
	Tag                  string    `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SuffixSet) Reset()         { *m = SuffixSet{} }
func (m *SuffixSet) String() string { return proto.CompactTextString(m) }
func (*SuffixSet) ProtoMessage()    {}
func (*SuffixSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e184749fd60cbd, []int{5}
}

func (m *SuffixSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuffixSet.Unmarshal(m, b)
}
func (m *SuffixSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuffixSet.Marshal(b, m, deterministic)
}
func (m *SuffixSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuffixSet.Merge(m, src)
}
func (m *SuffixSet) XXX_Size() int {
	return xxx_messageInfo_SuffixSet.Size(m)
}
func (m *SuffixSet) XXX_DiscardUnknown() {
	xxx_messageInfo_SuffixSet.DiscardUnknown(m)
}

var xxx_messageInfo_SuffixSet proto.InternalMessageInfo

func (m *SuffixSet) GetSuffixes() []*Suffix {
	if m != nil {
		return m.Suffixes
	}
	return nil
}

func (m *SuffixSet) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type TranslateRequest struct {
	// Types that are valid to be assigned to R:
	//	*TranslateRequest_TurkishLatin
	//	*TranslateRequest_Visenc
	//	*TranslateRequest_Ottoman
	R                    isTranslateRequest_R `protobuf_oneof:"r"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TranslateRequest) Reset()         { *m = TranslateRequest{} }
func (m *TranslateRequest) String() string { return proto.CompactTextString(m) }
func (*TranslateRequest) ProtoMessage()    {}
func (*TranslateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e184749fd60cbd, []int{6}
}

func (m *TranslateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranslateRequest.Unmarshal(m, b)
}
func (m *TranslateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranslateRequest.Marshal(b, m, deterministic)
}
func (m *TranslateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranslateRequest.Merge(m, src)
}
func (m *TranslateRequest) XXX_Size() int {
	return xxx_messageInfo_TranslateRequest.Size(m)
}
func (m *TranslateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TranslateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TranslateRequest proto.InternalMessageInfo

type isTranslateRequest_R interface {
	isTranslateRequest_R()
}

type TranslateRequest_TurkishLatin struct {
	TurkishLatin string `protobuf:"bytes,2,opt,name=turkishLatin,proto3,oneof"`
}

type TranslateRequest_Visenc struct {
	Visenc string `protobuf:"bytes,3,opt,name=visenc,proto3,oneof"`
}

type TranslateRequest_Ottoman struct {
	Ottoman string `protobuf:"bytes,4,opt,name=ottoman,proto3,oneof"`
}

func (*TranslateRequest_TurkishLatin) isTranslateRequest_R() {}

func (*TranslateRequest_Visenc) isTranslateRequest_R() {}

func (*TranslateRequest_Ottoman) isTranslateRequest_R() {}

func (m *TranslateRequest) GetR() isTranslateRequest_R {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *TranslateRequest) GetTurkishLatin() string {
	if x, ok := m.GetR().(*TranslateRequest_TurkishLatin); ok {
		return x.TurkishLatin
	}
	return ""
}

func (m *TranslateRequest) GetVisenc() string {
	if x, ok := m.GetR().(*TranslateRequest_Visenc); ok {
		return x.Visenc
	}
	return ""
}

func (m *TranslateRequest) GetOttoman() string {
	if x, ok := m.GetR().(*TranslateRequest_Ottoman); ok {
		return x.Ottoman
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TranslateRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TranslateRequest_TurkishLatin)(nil),
		(*TranslateRequest_Visenc)(nil),
		(*TranslateRequest_Ottoman)(nil),
	}
}

type TranslationWord struct {
	Root                 *Root                `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Suffixes             []*Suffix            `protobuf:"bytes,2,rep,name=suffixes,proto3" json:"suffixes,omitempty"`
	Remaining            string               `protobuf:"bytes,3,opt,name=remaining,proto3" json:"remaining,omitempty"`
	Direction            TranslationDirection `protobuf:"varint,4,opt,name=direction,proto3,enum=dervaze.TranslationDirection" json:"direction,omitempty"`
	OttomanRemaining     *OttomanWord         `protobuf:"bytes,5,opt,name=ottomanRemaining,proto3" json:"ottomanRemaining,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TranslationWord) Reset()         { *m = TranslationWord{} }
func (m *TranslationWord) String() string { return proto.CompactTextString(m) }
func (*TranslationWord) ProtoMessage()    {}
func (*TranslationWord) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e184749fd60cbd, []int{7}
}

func (m *TranslationWord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranslationWord.Unmarshal(m, b)
}
func (m *TranslationWord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranslationWord.Marshal(b, m, deterministic)
}
func (m *TranslationWord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranslationWord.Merge(m, src)
}
func (m *TranslationWord) XXX_Size() int {
	return xxx_messageInfo_TranslationWord.Size(m)
}
func (m *TranslationWord) XXX_DiscardUnknown() {
	xxx_messageInfo_TranslationWord.DiscardUnknown(m)
}

var xxx_messageInfo_TranslationWord proto.InternalMessageInfo

func (m *TranslationWord) GetRoot() *Root {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *TranslationWord) GetSuffixes() []*Suffix {
	if m != nil {
		return m.Suffixes
	}
	return nil
}

func (m *TranslationWord) GetRemaining() string {
	if m != nil {
		return m.Remaining
	}
	return ""
}

func (m *TranslationWord) GetDirection() TranslationDirection {
	if m != nil {
		return m.Direction
	}
	return TranslationDirection_tr2otm
}

func (m *TranslationWord) GetOttomanRemaining() *OttomanWord {
	if m != nil {
		return m.OttomanRemaining
	}
	return nil
}

type TranslationVariety struct {
	Varieties            []*TranslationWord   `protobuf:"bytes,1,rep,name=varieties,proto3" json:"varieties,omitempty"`
	Direction            TranslationDirection `protobuf:"varint,2,opt,name=direction,proto3,enum=dervaze.TranslationDirection" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TranslationVariety) Reset()         { *m = TranslationVariety{} }
func (m *TranslationVariety) String() string { return proto.CompactTextString(m) }
func (*TranslationVariety) ProtoMessage()    {}
func (*TranslationVariety) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e184749fd60cbd, []int{8}
}

func (m *TranslationVariety) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranslationVariety.Unmarshal(m, b)
}
func (m *TranslationVariety) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranslationVariety.Marshal(b, m, deterministic)
}
func (m *TranslationVariety) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranslationVariety.Merge(m, src)
}
func (m *TranslationVariety) XXX_Size() int {
	return xxx_messageInfo_TranslationVariety.Size(m)
}
func (m *TranslationVariety) XXX_DiscardUnknown() {
	xxx_messageInfo_TranslationVariety.DiscardUnknown(m)
}

var xxx_messageInfo_TranslationVariety proto.InternalMessageInfo

func (m *TranslationVariety) GetVarieties() []*TranslationWord {
	if m != nil {
		return m.Varieties
	}
	return nil
}

func (m *TranslationVariety) GetDirection() TranslationDirection {
	if m != nil {
		return m.Direction
	}
	return TranslationDirection_tr2otm
}

type TranslationSentence struct {
	Words                []*TranslationVariety `protobuf:"bytes,1,rep,name=words,proto3" json:"words,omitempty"`
	Direction            TranslationDirection  `protobuf:"varint,2,opt,name=direction,proto3,enum=dervaze.TranslationDirection" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TranslationSentence) Reset()         { *m = TranslationSentence{} }
func (m *TranslationSentence) String() string { return proto.CompactTextString(m) }
func (*TranslationSentence) ProtoMessage()    {}
func (*TranslationSentence) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e184749fd60cbd, []int{9}
}

func (m *TranslationSentence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranslationSentence.Unmarshal(m, b)
}
func (m *TranslationSentence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranslationSentence.Marshal(b, m, deterministic)
}
func (m *TranslationSentence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranslationSentence.Merge(m, src)
}
func (m *TranslationSentence) XXX_Size() int {
	return xxx_messageInfo_TranslationSentence.Size(m)
}
func (m *TranslationSentence) XXX_DiscardUnknown() {
	xxx_messageInfo_TranslationSentence.DiscardUnknown(m)
}

var xxx_messageInfo_TranslationSentence proto.InternalMessageInfo

func (m *TranslationSentence) GetWords() []*TranslationVariety {
	if m != nil {
		return m.Words
	}
	return nil
}

func (m *TranslationSentence) GetDirection() TranslationDirection {
	if m != nil {
		return m.Direction
	}
	return TranslationDirection_tr2otm
}

type TranslateResponse struct {
	Request              *TranslateRequest      `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Sentences            []*TranslationSentence `protobuf:"bytes,2,rep,name=sentences,proto3" json:"sentences,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *TranslateResponse) Reset()         { *m = TranslateResponse{} }
func (m *TranslateResponse) String() string { return proto.CompactTextString(m) }
func (*TranslateResponse) ProtoMessage()    {}
func (*TranslateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e184749fd60cbd, []int{10}
}

func (m *TranslateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranslateResponse.Unmarshal(m, b)
}
func (m *TranslateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranslateResponse.Marshal(b, m, deterministic)
}
func (m *TranslateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranslateResponse.Merge(m, src)
}
func (m *TranslateResponse) XXX_Size() int {
	return xxx_messageInfo_TranslateResponse.Size(m)
}
func (m *TranslateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TranslateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TranslateResponse proto.InternalMessageInfo

func (m *TranslateResponse) GetRequest() *TranslateRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *TranslateResponse) GetSentences() []*TranslationSentence {
	if m != nil {
		return m.Sentences
	}
	return nil
}

func init() {
	proto.RegisterEnum("dervaze.SearchType", SearchType_name, SearchType_value)
	proto.RegisterEnum("dervaze.Req", Req_name, Req_value)
	proto.RegisterEnum("dervaze.PartOfSpeech", PartOfSpeech_name, PartOfSpeech_value)
	proto.RegisterEnum("dervaze.TranslationDirection", TranslationDirection_name, TranslationDirection_value)
	proto.RegisterType((*SearchRequest)(nil), "dervaze.SearchRequest")
	proto.RegisterType((*OttomanWord)(nil), "dervaze.OttomanWord")
	proto.RegisterType((*Root)(nil), "dervaze.Root")
	proto.RegisterType((*RootSet)(nil), "dervaze.RootSet")
	proto.RegisterType((*Suffix)(nil), "dervaze.Suffix")
	proto.RegisterType((*SuffixSet)(nil), "dervaze.SuffixSet")
	proto.RegisterType((*TranslateRequest)(nil), "dervaze.TranslateRequest")
	proto.RegisterType((*TranslationWord)(nil), "dervaze.TranslationWord")
	proto.RegisterType((*TranslationVariety)(nil), "dervaze.TranslationVariety")
	proto.RegisterType((*TranslationSentence)(nil), "dervaze.TranslationSentence")
	proto.RegisterType((*TranslateResponse)(nil), "dervaze.TranslateResponse")
}

func init() { proto.RegisterFile("dervaze.proto", fileDescriptor_f7e184749fd60cbd) }

var fileDescriptor_f7e184749fd60cbd = []byte{
	// 1199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xdd, 0x6e, 0x1b, 0x45,
	0x1b, 0xf6, 0xfa, 0x27, 0xce, 0xbe, 0x4e, 0xe2, 0xed, 0x34, 0xcd, 0xb7, 0xcd, 0x17, 0x24, 0xb3,
	0x54, 0x60, 0x05, 0x64, 0x09, 0x07, 0x01, 0xa5, 0x07, 0x50, 0x37, 0x2e, 0xa1, 0x98, 0xc6, 0x9a,
	0x4d, 0xdd, 0x9f, 0x13, 0xb4, 0xf5, 0x8e, 0xe3, 0x05, 0x7b, 0xc7, 0x99, 0x19, 0xbb, 0x94, 0x63,
	0x38, 0x40, 0xe2, 0x2a, 0xb8, 0x17, 0xae, 0x81, 0x33, 0xee, 0x83, 0x13, 0x84, 0x66, 0x66, 0x7f,
	0xe3, 0x4d, 0x51, 0x85, 0x7a, 0xb6, 0xf3, 0x3c, 0x8f, 0xdf, 0x79, 0x7f, 0x67, 0xc6, 0xb0, 0xed,
	0x13, 0xb6, 0xf2, 0x7e, 0x24, 0x9d, 0x05, 0xa3, 0x82, 0xa2, 0x7a, 0xb4, 0x74, 0xfe, 0x32, 0x60,
	0xdb, 0x25, 0x1e, 0x1b, 0x4f, 0x31, 0xb9, 0x58, 0x12, 0x2e, 0xd0, 0x2e, 0x54, 0xbd, 0xa5, 0xa0,
	0xb6, 0xd1, 0x32, 0xda, 0xe6, 0x49, 0x09, 0xab, 0x15, 0xba, 0x05, 0x5b, 0x62, 0xc9, 0xbe, 0x0f,
	0xf8, 0x74, 0xe0, 0x89, 0x20, 0xb4, 0xcb, 0x11, 0x9b, 0x43, 0x91, 0x0d, 0x1b, 0xab, 0x80, 0x93,
	0x70, 0x6c, 0x57, 0x22, 0x3e, 0x5a, 0xa3, 0x7d, 0xa8, 0x53, 0x21, 0xe8, 0xdc, 0x0b, 0xed, 0x6a,
	0x44, 0xc5, 0x00, 0xda, 0x83, 0x9a, 0xf7, 0xfc, 0x3b, 0xcf, 0xb7, 0xeb, 0x2d, 0xa3, 0x5d, 0x3b,
	0x29, 0x61, 0xbd, 0x44, 0x47, 0x00, 0x5c, 0xb9, 0x76, 0xf6, 0x72, 0x41, 0xec, 0x9d, 0x96, 0xd1,
	0xde, 0xe9, 0x5e, 0xef, 0xc4, 0x81, 0xb8, 0x09, 0x85, 0x33, 0x32, 0xd4, 0x82, 0x06, 0x23, 0x7c,
	0x39, 0x13, 0x83, 0x60, 0x1e, 0x08, 0xbb, 0x29, 0x4d, 0xe2, 0x2c, 0xd4, 0xab, 0x43, 0x6d, 0x12,
	0x90, 0x99, 0xef, 0xfc, 0x6e, 0x40, 0xe3, 0x54, 0xfb, 0xf0, 0x98, 0x32, 0x1f, 0xed, 0x25, 0xde,
	0xab, 0xd8, 0x13, 0xdf, 0x6d, 0xa8, 0x2f, 0xc3, 0x60, 0x4c, 0x7d, 0xa2, 0xc3, 0xc6, 0xf1, 0x12,
	0xed, 0xc6, 0x9e, 0x57, 0xd4, 0x36, 0x91, 0xdf, 0xb7, 0x60, 0x5b, 0xff, 0x72, 0x40, 0x84, 0x20,
	0x8c, 0xdb, 0xd5, 0x56, 0xa5, 0x6d, 0xe2, 0x3c, 0x88, 0x0e, 0xc0, 0xd4, 0x6e, 0x7f, 0x4d, 0x5e,
	0xda, 0x35, 0x65, 0x37, 0x05, 0xd0, 0x21, 0x58, 0x3e, 0x15, 0x33, 0xc2, 0xb9, 0x9b, 0x88, 0x36,
	0x94, 0x68, 0x0d, 0x77, 0xfe, 0xa8, 0x42, 0x15, 0x53, 0x2a, 0x90, 0x73, 0xa9, 0x48, 0x3a, 0x8c,
	0x7c, 0x89, 0x3a, 0x69, 0x21, 0x64, 0x30, 0x8d, 0xee, 0x6e, 0x92, 0xd1, 0x4c, 0x2e, 0xd2, 0xe2,
	0x1c, 0x80, 0x39, 0xf3, 0xb8, 0x18, 0xd1, 0x17, 0x64, 0xa6, 0xab, 0x8a, 0x53, 0x40, 0x86, 0x2a,
	0x17, 0xf7, 0x68, 0xc8, 0x69, 0xe8, 0x85, 0x42, 0x17, 0x17, 0xe7, 0x41, 0xd4, 0x01, 0x44, 0x26,
	0x13, 0x32, 0x16, 0xc1, 0x8a, 0x0c, 0x12, 0x63, 0x3a, 0xe6, 0x02, 0x06, 0x7d, 0x04, 0x37, 0x12,
	0xf4, 0x2c, 0x1b, 0x90, 0xce, 0x40, 0x31, 0x89, 0xda, 0xd0, 0x4c, 0x88, 0x91, 0xae, 0x63, 0x5d,
	0xe9, 0x2f, 0xc3, 0x69, 0xd9, 0x36, 0xb3, 0x65, 0xbb, 0x0d, 0x5b, 0x0b, 0x8f, 0x89, 0xd3, 0x89,
	0xbb, 0x20, 0x64, 0x3c, 0xb5, 0x4d, 0xd5, 0x70, 0x37, 0x92, 0xf4, 0x0c, 0x33, 0x24, 0xce, 0x49,
	0x65, 0x1a, 0x48, 0xe8, 0xf3, 0xc7, 0x81, 0x98, 0xea, 0xd8, 0xac, 0x96, 0xd1, 0xde, 0xc4, 0x79,
	0x10, 0xbd, 0x0b, 0x3b, 0x53, 0x8f, 0xbb, 0x41, 0x78, 0x3e, 0x23, 0x5a, 0x76, 0x4d, 0xc9, 0x2e,
	0xa1, 0x71, 0x52, 0xd5, 0xe2, 0xc4, 0x63, 0xbe, 0x8d, 0xb4, 0xb5, 0x1c, 0x88, 0x3e, 0x80, 0x6b,
	0xb9, 0x2c, 0x2b, 0xe5, 0x75, 0xa5, 0x5c, 0x27, 0x64, 0x4a, 0xa7, 0x1e, 0x4f, 0x30, 0x97, 0x4e,
	0x04, 0x09, 0x83, 0xf0, 0xdc, 0xde, 0x55, 0xbf, 0x28, 0x26, 0x9d, 0x0e, 0xd4, 0x65, 0x63, 0xb9,
	0x44, 0xa0, 0x77, 0xa0, 0xc6, 0x28, 0x15, 0xdc, 0x36, 0x5a, 0x95, 0x76, 0xa3, 0xbb, 0x9d, 0xa4,
	0x45, 0x0a, 0xb0, 0xe6, 0x9c, 0x3f, 0x6b, 0xb0, 0xe1, 0x2e, 0x27, 0x93, 0xe0, 0x87, 0x37, 0xd2,
	0x8b, 0x1d, 0x40, 0x73, 0xca, 0x16, 0x53, 0x3a, 0xa3, 0xe7, 0xc1, 0xd8, 0x9b, 0xdd, 0x9b, 0x79,
	0x9c, 0x47, 0x4d, 0x59, 0xc0, 0xc8, 0x14, 0x31, 0x72, 0xb1, 0x0c, 0x18, 0xf1, 0xd3, 0xb6, 0xd3,
	0x1d, 0xba, 0x4e, 0xa0, 0x4f, 0xe4, 0xc9, 0xa1, 0x40, 0x3e, 0x3c, 0x75, 0x55, 0x7b, 0x5e, 0x59,
	0xfe, 0xac, 0x12, 0xf5, 0xe0, 0x46, 0xbc, 0xec, 0xe7, 0xba, 0x60, 0x43, 0x99, 0xd8, 0x4a, 0x53,
	0x45, 0x2e, 0x70, 0xb1, 0x14, 0x1d, 0xc3, 0x5e, 0x4c, 0x9c, 0xe4, 0x7b, 0xa4, 0x5e, 0x60, 0xe4,
	0x0a, 0x2d, 0x7a, 0x00, 0x37, 0x63, 0x66, 0xb0, 0xd6, 0x1b, 0x9b, 0x05, 0x86, 0xae, 0x96, 0xcb,
	0x71, 0xe2, 0x44, 0xf0, 0x24, 0x3f, 0x67, 0x54, 0x4d, 0x84, 0x89, 0x2f, 0xc3, 0x68, 0x00, 0xfb,
	0xb1, 0x99, 0x7b, 0x34, 0x14, 0x41, 0xb8, 0xf4, 0x44, 0x40, 0x43, 0xdd, 0x08, 0x36, 0x14, 0x6c,
	0xfb, 0x0a, 0x3d, 0xfa, 0x14, 0xfe, 0x17, 0x84, 0x2b, 0x6f, 0x16, 0xf8, 0x9e, 0x20, 0x1a, 0x53,
	0xd5, 0x24, 0xdc, 0x6e, 0xa8, 0x73, 0xf4, 0x2a, 0x1a, 0xdd, 0x81, 0xed, 0x31, 0x0d, 0x57, 0x84,
	0x09, 0x59, 0x16, 0x41, 0xed, 0xad, 0x57, 0x95, 0x30, 0xaf, 0x5d, 0x1f, 0xe1, 0xed, 0x82, 0x11,
	0x76, 0x1e, 0x80, 0xa9, 0xf7, 0x94, 0x23, 0xf1, 0x3e, 0x6c, 0x72, 0xb5, 0x20, 0xf1, 0x54, 0x34,
	0xd3, 0xdb, 0x49, 0x11, 0x38, 0x11, 0x20, 0x0b, 0x2a, 0xc2, 0x3b, 0x8f, 0x2e, 0x10, 0xf9, 0xe9,
	0x70, 0xb0, 0xce, 0x98, 0x17, 0xf2, 0x99, 0x27, 0x48, 0x7c, 0xf9, 0xbe, 0xc1, 0x6b, 0xb6, 0x57,
	0x01, 0x83, 0x39, 0x7f, 0x1b, 0xd0, 0x8c, 0x77, 0x0d, 0xa8, 0xbe, 0xf7, 0xde, 0x86, 0xaa, 0x1c,
	0x5f, 0x35, 0xa2, 0x6b, 0x93, 0xad, 0xa8, 0x5c, 0xa8, 0xe5, 0x7f, 0x0b, 0xf5, 0x00, 0x4c, 0x46,
	0xe6, 0x5e, 0xa0, 0xce, 0x97, 0xe8, 0xca, 0x48, 0x00, 0x74, 0x07, 0x4c, 0x3f, 0x60, 0xf2, 0x3c,
	0xa6, 0xda, 0xc9, 0x9d, 0xee, 0x5b, 0x89, 0xad, 0x8c, 0x6b, 0xc7, 0xb1, 0x08, 0xa7, 0x7a, 0xf4,
	0x05, 0x58, 0x51, 0x38, 0x38, 0xd9, 0xa1, 0xf6, 0x8a, 0xa3, 0x63, 0x4d, 0xed, 0xfc, 0x62, 0x00,
	0xca, 0xec, 0x32, 0xf2, 0x58, 0x40, 0xc4, 0x4b, 0xf4, 0x31, 0x98, 0x2b, 0xf5, 0x19, 0x24, 0xc5,
	0xb4, 0x8b, 0xbc, 0x52, 0x56, 0x53, 0x69, 0x3e, 0x9a, 0xf2, 0xeb, 0x45, 0xe3, 0xfc, 0x6c, 0xc0,
	0xf5, 0x8c, 0xc6, 0x25, 0xa1, 0x20, 0xe1, 0x98, 0xa0, 0x0f, 0xa1, 0xf6, 0x82, 0x32, 0x3f, 0x76,
	0xe4, 0xff, 0x45, 0x06, 0x23, 0xc7, 0xb1, 0x56, 0xfe, 0x37, 0x3f, 0x7e, 0x32, 0xe0, 0x5a, 0xa6,
	0x15, 0xf9, 0x82, 0x86, 0x9c, 0xa0, 0x23, 0xa8, 0x33, 0xdd, 0x96, 0x51, 0x67, 0xdc, 0x5c, 0x33,
	0x18, 0xf7, 0x2d, 0x8e, 0x95, 0xe8, 0x33, 0xf9, 0xaa, 0xd1, 0x61, 0xc4, 0x9d, 0x72, 0x50, 0xe4,
	0x47, 0x1c, 0x2b, 0x4e, 0xe5, 0x87, 0x1d, 0x80, 0xf4, 0x51, 0x87, 0x00, 0x36, 0x86, 0xb8, 0x7f,
	0xff, 0xab, 0x27, 0x56, 0x09, 0x99, 0x50, 0xbb, 0xff, 0xe8, 0xd9, 0xb3, 0xa7, 0x96, 0x21, 0x3f,
	0x71, 0xff, 0xcb, 0xfe, 0x13, 0xab, 0x7c, 0xf8, 0x1e, 0x54, 0x30, 0xb9, 0x90, 0xc8, 0xc3, 0xfe,
	0xa8, 0x8f, 0xb5, 0xee, 0x9b, 0xbb, 0x4f, 0x7b, 0x7d, 0xcb, 0x90, 0x3f, 0xbf, 0x3b, 0x78, 0x7c,
	0xf7, 0xa9, 0x6b, 0x95, 0x0f, 0x8f, 0x60, 0x2b, 0x3b, 0xfa, 0x68, 0x13, 0xaa, 0x0f, 0x4f, 0x1f,
	0x3d, 0xb4, 0x4a, 0xf2, 0x6b, 0xd4, 0xc7, 0x3d, 0xcb, 0x40, 0x4d, 0x68, 0x0c, 0xf1, 0xe9, 0xb0,
	0x8f, 0xbf, 0x55, 0x54, 0xf9, 0xb0, 0x03, 0xbb, 0x45, 0x79, 0x93, 0x86, 0x05, 0xeb, 0x52, 0x31,
	0xb7, 0x4a, 0xf2, 0x9b, 0x8a, 0x79, 0x57, 0x30, 0xcb, 0xe8, 0xfe, 0x5a, 0x86, 0xfa, 0xb1, 0x0e,
	0x14, 0x7d, 0x0e, 0x4d, 0xfd, 0xd4, 0x38, 0xa3, 0x51, 0x37, 0xa2, 0xc2, 0xfe, 0xdc, 0x2f, 0x44,
	0x9d, 0x92, 0x34, 0x10, 0x01, 0x67, 0x34, 0x7e, 0xb4, 0xbc, 0x96, 0x81, 0xdb, 0xd0, 0x88, 0x9e,
	0xf5, 0xf2, 0x62, 0x46, 0x7b, 0x97, 0x9e, 0xcd, 0x51, 0xdd, 0xf6, 0xad, 0xdc, 0xb0, 0xbb, 0x44,
	0x38, 0x25, 0x74, 0x0c, 0x66, 0x52, 0x5f, 0x74, 0x75, 0xcd, 0xf7, 0xf7, 0x8b, 0x28, 0xdd, 0x3b,
	0x4e, 0xa9, 0xd7, 0x86, 0xe6, 0x98, 0xce, 0x13, 0x09, 0x5b, 0x8c, 0x7b, 0x5b, 0x51, 0x7a, 0x86,
	0xf2, 0x2f, 0xc8, 0xd0, 0xf8, 0xad, 0x5c, 0x3d, 0xc6, 0xa3, 0x67, 0xcf, 0x37, 0xd4, 0x5f, 0x92,
	0xa3, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x83, 0xf3, 0xca, 0xed, 0xa3, 0x0c, 0x00, 0x00,
}
